version: "3.9"

services:
    app:
       build:
         context: .
         args:
          - DEV=true
       ports:
          - "8001:8001"
       volumes:
          - .:/app
       image: app:recipe_django
       container_name: recipe_django_container
       command: python manage.py runserver 0.0.0.0:8001
     
              